### PR TITLE
gpu-exporter-chart: add hostNetwork to the DS and make svc opt-out

### PR DESCRIPTION
**Pull request by KyriosGN0**
add the option to make DaemonSet with hostNetwork, also make the service with the option to opt out

### CODE REVIEW

**Review by utkuozdemir — APPROVED** [review]
LGTM, thank you!

**Comment by KyriosGN0** [comment]
@utkuozdemir should have I bumped the version?

**Comment by utkuozdemir** [comment]
It wouldn't trigger a release anyway, I need to do it manually, so no problem, I can also take care of it while doing that.

**Comment by KyriosGN0** [comment]
@utkuozdemir sorry for the ping, do you plan to bump the version chart soon ?

**Comment by utkuozdemir** [comment]
> @utkuozdemir sorry for the ping, do you plan to bump the version chart soon ?

I'll try to do it this weekend.

I also plan to move this chart soon out to its main repo and maybe publish it as OCI artifact (with oci://).

**Comment by utkuozdemir** [comment]
> > @utkuozdemir sorry for the ping, do you plan to bump the version chart soon ?
> 
> I'll try to do it this weekend.
> 
> I also plan to move this chart soon out to its main repo and maybe publish it as OCI artifact (with oci://).

done, released 1.0.0 with the exporter version 1.2.1 as default.

**Pull request merged**
